/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyPaymentRouteImport } from './routes/verify-payment'
import { Route as StudentPortalRouteImport } from './routes/student-portal'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminPanelRouteImport } from './routes/admin-panel'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicStudentPortalRouteImport } from './routes/api/public/student-portal'
import { Route as ApiPublicSendLeadMagnetRouteImport } from './routes/api/public/send-lead-magnet'
import { Route as ApiPublicMonnifyWebhookRouteImport } from './routes/api/public/monnify-webhook'
import { Route as ApiPublicAskNathyRouteImport } from './routes/api/public/ask-nathy'
import { Route as ApiPublicHooksTelegramWebhookRouteImport } from './routes/api/public/hooks/telegram-webhook'
import { Route as ApiPublicHooksSystemeioWebhookRouteImport } from './routes/api/public/hooks/systemeio-webhook'
import { Route as ApiPublicHooksMonthlyNewsletterRouteImport } from './routes/api/public/hooks/monthly-newsletter'
import { Route as ApiPublicHooksLivekitTokenRouteImport } from './routes/api/public/hooks/livekit-token'
import { Route as ApiPublicHooksLivekitDispatchRouteImport } from './routes/api/public/hooks/livekit-dispatch'
import { Route as ApiPublicHooksKeepAliveRouteImport } from './routes/api/public/hooks/keep-alive'
import { Route as ApiPublicHooksBudgetSummaryRouteImport } from './routes/api/public/hooks/budget-summary'
import { Route as ApiPublicHooksBirthdayGiftsRouteImport } from './routes/api/public/hooks/birthday-gifts'

const VerifyPaymentRoute = VerifyPaymentRouteImport.update({
  id: '/verify-payment',
  path: '/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPortalRoute = StudentPortalRouteImport.update({
  id: '/student-portal',
  path: '/student-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin-panel',
  path: '/admin-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicStudentPortalRoute = ApiPublicStudentPortalRouteImport.update({
  id: '/api/public/student-portal',
  path: '/api/public/student-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendLeadMagnetRoute = ApiPublicSendLeadMagnetRouteImport.update({
  id: '/api/public/send-lead-magnet',
  path: '/api/public/send-lead-magnet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMonnifyWebhookRoute = ApiPublicMonnifyWebhookRouteImport.update({
  id: '/api/public/monnify-webhook',
  path: '/api/public/monnify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAskNathyRoute = ApiPublicAskNathyRouteImport.update({
  id: '/api/public/ask-nathy',
  path: '/api/public/ask-nathy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTelegramWebhookRoute =
  ApiPublicHooksTelegramWebhookRouteImport.update({
    id: '/api/public/hooks/telegram-webhook',
    path: '/api/public/hooks/telegram-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSystemeioWebhookRoute =
  ApiPublicHooksSystemeioWebhookRouteImport.update({
    id: '/api/public/hooks/systemeio-webhook',
    path: '/api/public/hooks/systemeio-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonthlyNewsletterRoute =
  ApiPublicHooksMonthlyNewsletterRouteImport.update({
    id: '/api/public/hooks/monthly-newsletter',
    path: '/api/public/hooks/monthly-newsletter',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLivekitTokenRoute =
  ApiPublicHooksLivekitTokenRouteImport.update({
    id: '/api/public/hooks/livekit-token',
    path: '/api/public/hooks/livekit-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLivekitDispatchRoute =
  ApiPublicHooksLivekitDispatchRouteImport.update({
    id: '/api/public/hooks/livekit-dispatch',
    path: '/api/public/hooks/livekit-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksKeepAliveRoute = ApiPublicHooksKeepAliveRouteImport.update({
  id: '/api/public/hooks/keep-alive',
  path: '/api/public/hooks/keep-alive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBudgetSummaryRoute =
  ApiPublicHooksBudgetSummaryRouteImport.update({
    id: '/api/public/hooks/budget-summary',
    path: '/api/public/hooks/budget-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBirthdayGiftsRoute =
  ApiPublicHooksBirthdayGiftsRouteImport.update({
    id: '/api/public/hooks/birthday-gifts',
    path: '/api/public/hooks/birthday-gifts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-panel': typeof AdminPanelRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student-portal': typeof StudentPortalRoute
  '/verify-payment': typeof VerifyPaymentRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/api/public/ask-nathy': typeof ApiPublicAskNathyRoute
  '/api/public/monnify-webhook': typeof ApiPublicMonnifyWebhookRoute
  '/api/public/send-lead-magnet': typeof ApiPublicSendLeadMagnetRoute
  '/api/public/student-portal': typeof ApiPublicStudentPortalRoute
  '/api/public/hooks/birthday-gifts': typeof ApiPublicHooksBirthdayGiftsRoute
  '/api/public/hooks/budget-summary': typeof ApiPublicHooksBudgetSummaryRoute
  '/api/public/hooks/keep-alive': typeof ApiPublicHooksKeepAliveRoute
  '/api/public/hooks/livekit-dispatch': typeof ApiPublicHooksLivekitDispatchRoute
  '/api/public/hooks/livekit-token': typeof ApiPublicHooksLivekitTokenRoute
  '/api/public/hooks/monthly-newsletter': typeof ApiPublicHooksMonthlyNewsletterRoute
  '/api/public/hooks/systemeio-webhook': typeof ApiPublicHooksSystemeioWebhookRoute
  '/api/public/hooks/telegram-webhook': typeof ApiPublicHooksTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-panel': typeof AdminPanelRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student-portal': typeof StudentPortalRoute
  '/verify-payment': typeof VerifyPaymentRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/api/public/ask-nathy': typeof ApiPublicAskNathyRoute
  '/api/public/monnify-webhook': typeof ApiPublicMonnifyWebhookRoute
  '/api/public/send-lead-magnet': typeof ApiPublicSendLeadMagnetRoute
  '/api/public/student-portal': typeof ApiPublicStudentPortalRoute
  '/api/public/hooks/birthday-gifts': typeof ApiPublicHooksBirthdayGiftsRoute
  '/api/public/hooks/budget-summary': typeof ApiPublicHooksBudgetSummaryRoute
  '/api/public/hooks/keep-alive': typeof ApiPublicHooksKeepAliveRoute
  '/api/public/hooks/livekit-dispatch': typeof ApiPublicHooksLivekitDispatchRoute
  '/api/public/hooks/livekit-token': typeof ApiPublicHooksLivekitTokenRoute
  '/api/public/hooks/monthly-newsletter': typeof ApiPublicHooksMonthlyNewsletterRoute
  '/api/public/hooks/systemeio-webhook': typeof ApiPublicHooksSystemeioWebhookRoute
  '/api/public/hooks/telegram-webhook': typeof ApiPublicHooksTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin-panel': typeof AdminPanelRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student-portal': typeof StudentPortalRoute
  '/verify-payment': typeof VerifyPaymentRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/api/public/ask-nathy': typeof ApiPublicAskNathyRoute
  '/api/public/monnify-webhook': typeof ApiPublicMonnifyWebhookRoute
  '/api/public/send-lead-magnet': typeof ApiPublicSendLeadMagnetRoute
  '/api/public/student-portal': typeof ApiPublicStudentPortalRoute
  '/api/public/hooks/birthday-gifts': typeof ApiPublicHooksBirthdayGiftsRoute
  '/api/public/hooks/budget-summary': typeof ApiPublicHooksBudgetSummaryRoute
  '/api/public/hooks/keep-alive': typeof ApiPublicHooksKeepAliveRoute
  '/api/public/hooks/livekit-dispatch': typeof ApiPublicHooksLivekitDispatchRoute
  '/api/public/hooks/livekit-token': typeof ApiPublicHooksLivekitTokenRoute
  '/api/public/hooks/monthly-newsletter': typeof ApiPublicHooksMonthlyNewsletterRoute
  '/api/public/hooks/systemeio-webhook': typeof ApiPublicHooksSystemeioWebhookRoute
  '/api/public/hooks/telegram-webhook': typeof ApiPublicHooksTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-panel'
    | '/login'
    | '/signup'
    | '/student-portal'
    | '/verify-payment'
    | '/admin'
    | '/portal'
    | '/api/public/ask-nathy'
    | '/api/public/monnify-webhook'
    | '/api/public/send-lead-magnet'
    | '/api/public/student-portal'
    | '/api/public/hooks/birthday-gifts'
    | '/api/public/hooks/budget-summary'
    | '/api/public/hooks/keep-alive'
    | '/api/public/hooks/livekit-dispatch'
    | '/api/public/hooks/livekit-token'
    | '/api/public/hooks/monthly-newsletter'
    | '/api/public/hooks/systemeio-webhook'
    | '/api/public/hooks/telegram-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-panel'
    | '/login'
    | '/signup'
    | '/student-portal'
    | '/verify-payment'
    | '/admin'
    | '/portal'
    | '/api/public/ask-nathy'
    | '/api/public/monnify-webhook'
    | '/api/public/send-lead-magnet'
    | '/api/public/student-portal'
    | '/api/public/hooks/birthday-gifts'
    | '/api/public/hooks/budget-summary'
    | '/api/public/hooks/keep-alive'
    | '/api/public/hooks/livekit-dispatch'
    | '/api/public/hooks/livekit-token'
    | '/api/public/hooks/monthly-newsletter'
    | '/api/public/hooks/systemeio-webhook'
    | '/api/public/hooks/telegram-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-panel'
    | '/login'
    | '/signup'
    | '/student-portal'
    | '/verify-payment'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/api/public/ask-nathy'
    | '/api/public/monnify-webhook'
    | '/api/public/send-lead-magnet'
    | '/api/public/student-portal'
    | '/api/public/hooks/birthday-gifts'
    | '/api/public/hooks/budget-summary'
    | '/api/public/hooks/keep-alive'
    | '/api/public/hooks/livekit-dispatch'
    | '/api/public/hooks/livekit-token'
    | '/api/public/hooks/monthly-newsletter'
    | '/api/public/hooks/systemeio-webhook'
    | '/api/public/hooks/telegram-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminPanelRoute: typeof AdminPanelRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StudentPortalRoute: typeof StudentPortalRoute
  VerifyPaymentRoute: typeof VerifyPaymentRoute
  ApiPublicAskNathyRoute: typeof ApiPublicAskNathyRoute
  ApiPublicMonnifyWebhookRoute: typeof ApiPublicMonnifyWebhookRoute
  ApiPublicSendLeadMagnetRoute: typeof ApiPublicSendLeadMagnetRoute
  ApiPublicStudentPortalRoute: typeof ApiPublicStudentPortalRoute
  ApiPublicHooksBirthdayGiftsRoute: typeof ApiPublicHooksBirthdayGiftsRoute
  ApiPublicHooksBudgetSummaryRoute: typeof ApiPublicHooksBudgetSummaryRoute
  ApiPublicHooksKeepAliveRoute: typeof ApiPublicHooksKeepAliveRoute
  ApiPublicHooksLivekitDispatchRoute: typeof ApiPublicHooksLivekitDispatchRoute
  ApiPublicHooksLivekitTokenRoute: typeof ApiPublicHooksLivekitTokenRoute
  ApiPublicHooksMonthlyNewsletterRoute: typeof ApiPublicHooksMonthlyNewsletterRoute
  ApiPublicHooksSystemeioWebhookRoute: typeof ApiPublicHooksSystemeioWebhookRoute
  ApiPublicHooksTelegramWebhookRoute: typeof ApiPublicHooksTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-payment': {
      id: '/verify-payment'
      path: '/verify-payment'
      fullPath: '/verify-payment'
      preLoaderRoute: typeof VerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-portal': {
      id: '/student-portal'
      path: '/student-portal'
      fullPath: '/student-portal'
      preLoaderRoute: typeof StudentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel': {
      id: '/admin-panel'
      path: '/admin-panel'
      fullPath: '/admin-panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/student-portal': {
      id: '/api/public/student-portal'
      path: '/api/public/student-portal'
      fullPath: '/api/public/student-portal'
      preLoaderRoute: typeof ApiPublicStudentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-lead-magnet': {
      id: '/api/public/send-lead-magnet'
      path: '/api/public/send-lead-magnet'
      fullPath: '/api/public/send-lead-magnet'
      preLoaderRoute: typeof ApiPublicSendLeadMagnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monnify-webhook': {
      id: '/api/public/monnify-webhook'
      path: '/api/public/monnify-webhook'
      fullPath: '/api/public/monnify-webhook'
      preLoaderRoute: typeof ApiPublicMonnifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ask-nathy': {
      id: '/api/public/ask-nathy'
      path: '/api/public/ask-nathy'
      fullPath: '/api/public/ask-nathy'
      preLoaderRoute: typeof ApiPublicAskNathyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-webhook': {
      id: '/api/public/hooks/telegram-webhook'
      path: '/api/public/hooks/telegram-webhook'
      fullPath: '/api/public/hooks/telegram-webhook'
      preLoaderRoute: typeof ApiPublicHooksTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/systemeio-webhook': {
      id: '/api/public/hooks/systemeio-webhook'
      path: '/api/public/hooks/systemeio-webhook'
      fullPath: '/api/public/hooks/systemeio-webhook'
      preLoaderRoute: typeof ApiPublicHooksSystemeioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monthly-newsletter': {
      id: '/api/public/hooks/monthly-newsletter'
      path: '/api/public/hooks/monthly-newsletter'
      fullPath: '/api/public/hooks/monthly-newsletter'
      preLoaderRoute: typeof ApiPublicHooksMonthlyNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/livekit-token': {
      id: '/api/public/hooks/livekit-token'
      path: '/api/public/hooks/livekit-token'
      fullPath: '/api/public/hooks/livekit-token'
      preLoaderRoute: typeof ApiPublicHooksLivekitTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/livekit-dispatch': {
      id: '/api/public/hooks/livekit-dispatch'
      path: '/api/public/hooks/livekit-dispatch'
      fullPath: '/api/public/hooks/livekit-dispatch'
      preLoaderRoute: typeof ApiPublicHooksLivekitDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/keep-alive': {
      id: '/api/public/hooks/keep-alive'
      path: '/api/public/hooks/keep-alive'
      fullPath: '/api/public/hooks/keep-alive'
      preLoaderRoute: typeof ApiPublicHooksKeepAliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/budget-summary': {
      id: '/api/public/hooks/budget-summary'
      path: '/api/public/hooks/budget-summary'
      fullPath: '/api/public/hooks/budget-summary'
      preLoaderRoute: typeof ApiPublicHooksBudgetSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/birthday-gifts': {
      id: '/api/public/hooks/birthday-gifts'
      path: '/api/public/hooks/birthday-gifts'
      fullPath: '/api/public/hooks/birthday-gifts'
      preLoaderRoute: typeof ApiPublicHooksBirthdayGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminPanelRoute: AdminPanelRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StudentPortalRoute: StudentPortalRoute,
  VerifyPaymentRoute: VerifyPaymentRoute,
  ApiPublicAskNathyRoute: ApiPublicAskNathyRoute,
  ApiPublicMonnifyWebhookRoute: ApiPublicMonnifyWebhookRoute,
  ApiPublicSendLeadMagnetRoute: ApiPublicSendLeadMagnetRoute,
  ApiPublicStudentPortalRoute: ApiPublicStudentPortalRoute,
  ApiPublicHooksBirthdayGiftsRoute: ApiPublicHooksBirthdayGiftsRoute,
  ApiPublicHooksBudgetSummaryRoute: ApiPublicHooksBudgetSummaryRoute,
  ApiPublicHooksKeepAliveRoute: ApiPublicHooksKeepAliveRoute,
  ApiPublicHooksLivekitDispatchRoute: ApiPublicHooksLivekitDispatchRoute,
  ApiPublicHooksLivekitTokenRoute: ApiPublicHooksLivekitTokenRoute,
  ApiPublicHooksMonthlyNewsletterRoute: ApiPublicHooksMonthlyNewsletterRoute,
  ApiPublicHooksSystemeioWebhookRoute: ApiPublicHooksSystemeioWebhookRoute,
  ApiPublicHooksTelegramWebhookRoute: ApiPublicHooksTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
